package com.oracle.five.cloud_disk.mapper;

import com.oracle.five.cloud_disk.beans.Relationship;
import com.oracle.five.cloud_disk.beans.User;

import java.util.List;

import org.springframework.stereotype.Repository;
@Repository
public interface RelationshipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RELATIONSHIP
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    boolean deleteByPrimaryKey(Integer relationshipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RELATIONSHIP
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    int insert(Relationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RELATIONSHIP
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    Relationship selectByPrimaryKey(Integer relationshipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RELATIONSHIP
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    List<Relationship> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RELATIONSHIP
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    int updateByPrimaryKey(Relationship record);
    boolean getBothRelate(Integer userId, Integer loginedUserId);

	List<User> getFriendList(Integer loginedUserId);

	boolean addRemark(Relationship relationship);
}