package com.oracle.five.cloud_disk.mapper;

import com.oracle.five.cloud_disk.beans.Share;

import java.util.List;

import org.springframework.stereotype.Repository;
@Repository
public interface ShareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHARE
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    int deleteByPrimaryKey(Integer shareId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHARE
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    int insert(Share record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHARE
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    Share selectByPrimaryKey(Integer shareId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHARE
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    List<Share> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHARE
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    int updateByPrimaryKey(Share record);
    
    Share selectsharelinkbylink(String link);
}