package com.oracle.five.cloud_disk.mapper;

import org.springframework.stereotype.Repository;

import com.oracle.five.cloud_disk.beans.CloudFile;
import com.oracle.five.cloud_disk.beans.User;
@Repository
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERS
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
   // int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERS
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    ///int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERS
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    User selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERS
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
   // List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERS
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    //int updateByPrimaryKey(User record);
	public boolean adduser(User user);
	public int login(User user);
	public int selectuserbyname(String nickname);
	public boolean insertfile();
	public int fileid();
	public int selectuseridbyname(String nickname);
	public String selectuserimgbyname(String nickname);
	public int selectusercapacitybyname(String nickname);
	public CloudFile selectuserfilebyname(String nickname);
	public int selectfileidbyname(String nickname);
	public User getUserByNickname(String nickname);
	
	
}