package com.oracle.five.cloud_disk.beans;

import java.util.Date;

public class ChatRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAT_RECORD.RECORD_ID
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    private Integer recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAT_RECORD.CONKTENT
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    private String conktent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAT_RECORD.RECORD_TIME
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    private Date recordTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAT_RECORD.TYPE
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAT_RECORD.FILE_ID
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    private CloudFile cloudFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAT_RECORD.DIALOGUE_ID
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    private Dialogue dialogue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAT_RECORD.RECORD_ID
     *
     * @return the value of CHAT_RECORD.RECORD_ID
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAT_RECORD.RECORD_ID
     *
     * @param recordId the value for CHAT_RECORD.RECORD_ID
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAT_RECORD.CONKTENT
     *
     * @return the value of CHAT_RECORD.CONKTENT
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public String getConktent() {
        return conktent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAT_RECORD.CONKTENT
     *
     * @param conktent the value for CHAT_RECORD.CONKTENT
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public void setConktent(String conktent) {
        this.conktent = conktent == null ? null : conktent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAT_RECORD.RECORD_TIME
     *
     * @return the value of CHAT_RECORD.RECORD_TIME
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public Date getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAT_RECORD.RECORD_TIME
     *
     * @param recordTime the value for CHAT_RECORD.RECORD_TIME
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAT_RECORD.TYPE
     *
     * @return the value of CHAT_RECORD.TYPE
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAT_RECORD.TYPE
     *
     * @param type the value for CHAT_RECORD.TYPE
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    

    public CloudFile getCloudFile() {
		return cloudFile;
	}

	public void setCloudFile(CloudFile cloudFile) {
		this.cloudFile = cloudFile;
	}

	public Dialogue getDialogue() {
		return dialogue;
	}

	public void setDialogue(Dialogue dialogue) {
		this.dialogue = dialogue;
	}

	
}