package com.oracle.five.cloud_disk.beans;

import java.util.Date;
import java.util.List;

public class Share {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHARE.SHARE_ID
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    private Integer shareId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHARE.SHARE_TYPE
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    private Integer shareType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHARE.PASSWORD
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHARE.SHARE_TIME
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    private Date shareTime;
    
    private String sharelink;
    
    private int timerange;
    
    
    public int getTimerange() {
		return timerange;
	}

	public void setTimerange(int timerange) {
		this.timerange = timerange;
	}

	public String getSharelink() {
		return sharelink;
	}

	public void setSharelink(String sharelink) {
		this.sharelink = sharelink;
	}

	private List<CloudFile> files;
    

    public List<CloudFile> getFiles() {
		return files;
	}

	public void setFiles(List<CloudFile> files) {
		this.files = files;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHARE.SHARE_ID
     *
     * @return the value of SHARE.SHARE_ID
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public Integer getShareId() {
        return shareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHARE.SHARE_ID
     *
     * @param shareId the value for SHARE.SHARE_ID
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public void setShareId(Integer shareId) {
        this.shareId = shareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHARE.SHARE_TYPE
     *
     * @return the value of SHARE.SHARE_TYPE
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public Integer getShareType() {
        return shareType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHARE.SHARE_TYPE
     *
     * @param shareType the value for SHARE.SHARE_TYPE
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public void setShareType(Integer shareType) {
        this.shareType = shareType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHARE.PASSWORD
     *
     * @return the value of SHARE.PASSWORD
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHARE.PASSWORD
     *
     * @param password the value for SHARE.PASSWORD
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHARE.SHARE_TIME
     *
     * @return the value of SHARE.SHARE_TIME
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public Date getShareTime() {
        return shareTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHARE.SHARE_TIME
     *
     * @param shareTime the value for SHARE.SHARE_TIME
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public void setShareTime(Date shareTime) {
        this.shareTime = shareTime;
    }
}