package com.oracle.five.cloud_disk.beans;

import java.util.List;

public class Dialogue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIALOGUE.DIALOGUE_ID
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    private Integer dialogueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIALOGUE.HOST_USER_ID
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    private User hostUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIALOGUE.TO_USER_ID
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    private User toUser;
    private List<ChatRecord> chatRecords;
    

    public List<ChatRecord> getChatRecords() {
		return chatRecords;
	}

	public void setChatRecords(List<ChatRecord> chatRecords) {
		this.chatRecords = chatRecords;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIALOGUE.DIALOGUE_ID
     *
     * @return the value of DIALOGUE.DIALOGUE_ID
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public Integer getDialogueId() {
        return dialogueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIALOGUE.DIALOGUE_ID
     *
     * @param dialogueId the value for DIALOGUE.DIALOGUE_ID
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public void setDialogueId(Integer dialogueId) {
        this.dialogueId = dialogueId;
    }

	public User getHostUser() {
		return hostUser;
	}

	public void setHostUser(User hostUser) {
		this.hostUser = hostUser;
	}

	public User getToUser() {
		return toUser;
	}

	public void setToUser(User toUser) {
		this.toUser = toUser;
	}

    
}