package com.oracle.five.cloud_disk.beans;

import java.util.List;

public class User {
    public static final String ME="ME",FRIEND="FRIEND",STRANGER="STRANGER";
    private Integer userId;

    private String password;

    private String nickname;

    private String headImg;

    private Integer capacity;

    private CloudFile rootFile;
    
    private List<User> friends;
    private List<Dialogue> dialogues;
    private String who;
    
    
   

	public String getWho() {
		return who;
	}

	public void setWho(String who) {
		this.who = who;
	}

	public List<Dialogue> getDialogues() {
		return dialogues;
	}

	public void setDialogues(List<Dialogue> dialogues) {
		this.dialogues = dialogues;
	}

	public List<User> getFriends() {
		return friends;
	}

	public void setFriends(List<User> friends) {
		this.friends = friends;
	}

	public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.USER_ID
     *
     * @param userId the value for USERS.USER_ID
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.PASSWORD
     *
     * @return the value of USERS.PASSWORD
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.PASSWORD
     *
     * @param password the value for USERS.PASSWORD
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.NICKNAME
     *
     * @return the value of USERS.NICKNAME
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.NICKNAME
     *
     * @param nickname the value for USERS.NICKNAME
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.HEAD_IMG
     *
     * @return the value of USERS.HEAD_IMG
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public String getHeadImg() {
        return headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.HEAD_IMG
     *
     * @param headImg the value for USERS.HEAD_IMG
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public void setHeadImg(String headImg) {
        this.headImg = headImg == null ? null : headImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.CAPACITY
     *
     * @return the value of USERS.CAPACITY
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public Integer getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.CAPACITY
     *
     * @param capacity the value for USERS.CAPACITY
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }

	public CloudFile getRootFile() {
		return rootFile;
	}

	public void setRootFile(CloudFile rootFile) {
		this.rootFile = rootFile;
	}

	public User(String password, String nickname, String headImg) {
		super();
		this.password = password;
		this.nickname = nickname;
		this.headImg = headImg;
	}

	public User(String password, String nickname) {
		super();
		this.password = password;
		this.nickname = nickname;
	}

	public User(Integer userId, String nickname, String headImg, Integer capacity, CloudFile rootFile) {
		super();
		this.userId = userId;
		this.nickname = nickname;
		this.headImg = headImg;
		this.capacity = capacity;
		this.rootFile = rootFile;
	}

	public User(String password, String nickname, String headImg, CloudFile rootFile) {
		super();
		this.password = password;
		this.nickname = nickname;
		this.headImg = headImg;
		this.rootFile = rootFile;
	}

	public User() {
		super();
		// TODO Auto-generated constructor stub
	}

	

	@Override
	public String toString() {
		return "User [userId=" + userId + ", password=" + password + ", nickname=" + nickname + ", headImg=" + headImg
				+ ", capacity=" + capacity + ", rootFile=" + rootFile + ", friends=" + friends + ", dialogues="
				+ dialogues + "]";
	}

    
}